# 访客统计配置文件
# Visitor Statistics Configuration

# 基本设置
visitor_stats:
  enabled: true
  # 显示位置
  position: "top"  # top, bottom, sidebar
  
  # 显示项目
  display:
    total_visits: true
    daily_visits: true
    online_count: true
    visitor_location: true
    visitor_ip: true
    current_time: true
  
  # 隐私设置
  privacy:
    mask_ip: true  # 是否隐藏IP的部分信息
    show_full_location: false  # 是否显示完整地址
    
  # 样式设置
  theme:
    color_scheme: "gradient"  # gradient, solid, minimal
    primary_color: "#667eea"
    secondary_color: "#764ba2"
    mobile_friendly: true
    
  # API配置
  api:
    # 主要API (推荐使用ipapi.co，免费且稳定)
    primary_endpoint: "https://ipapi.co/json/"
    
    # 备用API列表
    backup_endpoints:
      - "https://freeipapi.com/api/json/"
      - "https://api.ipify.org?format=json"
    
    # 请求配置
    timeout: 5000  # 请求超时时间(毫秒)
    retry_attempts: 3
    retry_delay: 2000  # 重试延迟(毫秒)
    
  # 缓存设置
  cache:
    location_cache_duration: 86400000  # 24小时 (毫秒)
    stats_update_interval: 60000  # 1分钟 (毫秒)
    
  # 数据保留
  data_retention:
    daily_stats_days: 30  # 保留30天的日统计
    session_timeout: 1800000  # 30分钟会话超时 (毫秒)
    max_sessions: 100  # 最多保留100个会话记录
    
  # 高级功能
  advanced:
    # 在线人数算法
    online_users_algorithm: "time_based"  # time_based, random, hybrid
    
    # 地理位置功能
    show_country_flag: true
    show_timezone: false
    show_isp: false
    
    # 交互功能
    click_animation: true
    refresh_button: true
    double_tap_refresh: true  # 移动端双击刷新
    
    # 调试模式
    debug_mode: false
    console_logging: false

# 多语言支持
i18n:
  zh_CN:
    total_visits: "总访问量"
    daily_visits: "今日访问"
    online_count: "在线人数"
    loading_location: "正在获取位置信息..."
    loading_ip: "正在获取IP信息..."
    location_failed: "位置信息获取失败"
    ip_failed: "获取失败"
    refresh_tooltip: "刷新位置信息"
    current_time: "当前时间"
  
  en_US:
    total_visits: "Total Visits"
    daily_visits: "Today's Visits"
    online_count: "Online Users"
    loading_location: "Getting location..."
    loading_ip: "Getting IP info..."
    location_failed: "Failed to get location"
    ip_failed: "Failed to get IP"
    refresh_tooltip: "Refresh location info"
    current_time: "Current Time"

# 响应式设计
responsive:
  # 断点设置
  breakpoints:
    mobile: 768
    tablet: 1024
    desktop: 1200
  
  # 移动端设置
  mobile:
    use_compact_view: true
    show_simplified_location: true
    enable_touch_interactions: true
    
  # 桌面端设置
  desktop:
    show_detailed_stats: true
    enable_hover_effects: true
    
# 性能优化
performance:
  # 懒加载
  lazy_load: true
  
  # 预加载资源
  preload_fonts: false
  
  # 代码分割
  code_splitting: false
  
  # 最小化请求
  minimize_api_calls: true

# 兼容性设置
compatibility:
  # 浏览器支持
  ie_support: false
  legacy_browsers: false
  
  # 功能降级
  fallback_to_basic: true
  graceful_degradation: true

# 统计分析 (可选)
analytics:
  # 是否启用内置分析
  enable_built_in: false
  
  # Google Analytics 集成
  ga_tracking: false
  ga_events:
    track_visits: false
    track_location_requests: false
    
  # 自定义事件
  custom_events:
    visit_milestone: false  # 访问量里程碑事件
    location_change: false  # 位置变化事件

# 安全设置
security:
  # 内容安全策略
  csp_compliant: true
  
  # 跨域请求
  cors_handling: "strict"
  
  # 数据加密
  encrypt_stored_data: false
  
  # 隐私保护
  respect_dnt: true  # 尊重 Do Not Track 设置
  anonymize_data: true

# 自定义样式覆盖
custom_styles: |
  /* 在这里添加自定义CSS */
  .visitor-stats-container {
    /* 自定义样式 */
  }

# 自定义脚本
custom_scripts: |
  // 在这里添加自定义JavaScript
  // 例如：自定义事件处理、第三方集成等
